### ISSUE TITLE
Can't Edit Worldmap Files

### ISSUE THREAD

**Issue by Karkus476** [SuperTux/flexlay#35]
Traceback (most recent call last):
  File "supertux/gui.py", line 544, in load_level
    self.load_worldmap(filename)
  File "/supertux/gui.py", line 561, in load_worldmap
    worldmap = WorldMap(filename)
  File "supertux/worldmap.py", line 51, in **init**
    tree = load_lisp(self.filename, "supertux-worldmap")
  File "supertux/util.py", line 30, in load_lisp
    raise Exception("Error: '%s' is not a '%s' file" % (filename, root_symbol))
Exception: Error: 'data/levels/world1/worldmap.stwm' is not a 'supertux-worldmap' file

**Comment by Karkus476** [comment]
@tobbi Argh, this is a pain. Can you remember when the worldmap format was last changed by any chance? The flexlay editor is looking for [this](http://supertux.lethargik.org/wiki/File_formats#Worldmaps), when they actually appear:
[worldmap.stwm.txt](https://github.com/SuperTux/flexlay/files/40831/worldmap.stwm.txt)

**Comment by Karkus476** [comment]
Trying to use normal level loading code with the worldmap tileset doesn't work either, the wrong tiles are displayed.
![screenshot from 2015-11-22 00 47 13](https://cloud.githubusercontent.com/assets/14023329/11321341/c13761c6-90b2-11e5-8457-3b3c3e717de0.png)

**Comment by brmbrmcar** [comment]
I get Exception: Error: '/usr/share/games/supertux2/levels/world1/worldmap.stwm' is not a 'supertux-worldmap' file

**Comment by Karkus476** [comment]
This is because the editor is expecting an older worlmap format.
- Karkus

**Comment by brmbrmcar** [comment]
Will it get fixed?

**Comment by Hypernoot** [comment]
It looks like wrong tileset is loaded.

**Comment by Karkus476** [comment]
@Hume2 I changed the tileset as well. Assuming [this](https://github.com/SuperTux/supertux/blob/master/data/images/worldmap.strf) is the correct tileset

**Comment by Karkus476** [comment]
@brmbrmcar Yes, I don't intend to leave it broken

**Comment by Karkus476** [comment]
Awkwardly, you still can't edit World 1's world map, because of #1

**Comment by Hypernoot** [comment]
@Karkus476 This is not the correct tileset. Use ice_world.strf.

**Comment by Karkus476** [comment]
Yes, thanks, I have sorted that out.
- Karkus

**Comment by tobbi** [comment]
I added loading of the correct tileset if it isn't the current one in a recent commit. Can you guys check it out?

**Comment by Karkus476** [comment]
@tobbi I've checked it out. It works great, thanks!
