### ISSUE TITLE
Create a "Resource library" instead of specifying file paths

### ISSUE THREAD

**Issue by tobbi** [SuperTux/flexlay#39]
Specifying sprite filenames for badguys each time is simply bad. IMO we should scan for .sprite files and add them to a "Sprite library". Then selecting a sprite would be much easier!

Actually, let's create a resource library! Makes it much easier to deal with resources of any kind.

**Comment by Karkus476** [comment]
@tobbi So what you want to stop is [this](https://github.com/SuperTux/flexlay/blob/develop/supertux/gameobj_factor.py#L95) right?

**Comment by tobbi** [comment]
Actually, factories can remain. I just think we should scan for .sprite files and get their properties and then add them. In case people want to create custom game objects, we can let them add directories which get scanned as well.

**Comment by Karkus476** [comment]
Okay, I'll see if I can do that

**Comment by Karkus476** [comment]
9010b8b2d01e did not solve this though, it just moved the hardcoded sprites elsewhere.
