### ISSUE TITLE
'Project' Tab

### ISSUE THREAD

**Issue by Karkus476** [SuperTux/flexlay#4]
A QTreeView which mirrors the format of the level file's s-expr tree

**Comment by tobbi** [comment]
For the design, I'm thinking about something like the menu on the right (could be on the left side, though):
http://static.icsharpcode.net/OpenSource/SD/TeaserSharpDevelop2OnVista.png

**Comment by Karkus476** [comment]
I think this could be implemented as a 'project' tab. This would be a tree view as you suggested, and would mirror the sexpr tree in the file. Clicking on the items in that would open them in the properties tab which I've already created
