### ISSUE TITLE
Improve user-friendliness of layers

### ISSUE THREAD

**Issue by maxteufel** [SuperTux/flexlay#60]
- [ ] In the overview, show z-index and button to change visibility next to each layer
- [x] You can't add/remove any layers: #1
- [ ] #58, but there's even more options than z-index and solid
- [ ] Treat particles, such as rain, snow and ghosts, as well as thunderstorms as layer instead of showing them as object in the level
- [ ] Always order tilemaps correctly (by z-pos) in selector and editormap (e.g. when undoing delete)

**Comment by Karkus476** [comment]
@maxteufel What else other than z-pos and solid?

**Comment by maxteufel** [comment]
The C# level editor also provides me with options for: Speed (number), SpeedY (number), DrawTarget (normal/lightmap), Alpha (number), and I don't know if that's already implemented, Name (string).

For the numbers I'm not sure if they're integers or floats.

Furthermore, when treating thunderstroms as layers, they have Running (boolean), Name (string) and Interval (number, in seconds I assume) options.

Thunderstorms and particles do have a z-index option, but not a solid option.

**Comment by Hypernoot** [comment]
Those numbers are floats.

**Comment by Karkus476** [comment]
@maxteufel You can edit the name by double clicking
