### ISSUE TITLE
Fix Tile Selector Layout

### ISSUE THREAD

**Issue by ghost** [SuperTux/flexlay#69]
The tile selector layout on the mono/c# editor is much cleaner and faster to select, because you can just hold down the right mouse button and select the group of tiles to put on your level. But in the flexlay level editor, the tiles are mixed up making it so that you have to select each tile separately.
See in images below:

<b><h4>Flexlay Level Editor:</h4></b>

![screenshot from 2016-01-06 15 03 53](https://cloud.githubusercontent.com/assets/16365176/12153473/fc64ec16-b487-11e5-9442-d039476bc012.png)

<b><h4>Mono/C# Editor:</h4></b>

![screenshot from 2016-01-06 15 06 11](https://cloud.githubusercontent.com/assets/16365176/12153493/16fea26a-b488-11e5-83d5-78d2565cc4b1.png)

This would make a big difference in the speed of level design with flexlay if you could add it in.

**Comment by Karkus476** [comment]
@Jake41 Thanks for creating a high quality bug report on this issue. I will attempt to fix this as soon as possible

**Comment by Hypernoot** [comment]
As you can notice the tiles are in the same order, but in Mono/C# editor there are only 4 colums.

**Comment by Karkus476** [comment]
Yes, I think I will set it to default to four columns.
- Karkus
