### ISSUE TITLE
Add support for brushes

### ISSUE THREAD

**Issue by maxteufel** [SuperTux/flexlay#70]
Another feature useful to make level designing faster (also ref: #69) would be brushes, as currently implemented in the C# editor (https://github.com/SuperTux/supertux-editor/tree/master/data/brushes).

**Comment by tobbi** [comment]
ref #18 as well.

**Comment by Karkus476** [comment]
@SuperTux/developers For portability (between in game and various external editors) I suggest these files be added to the data directory.

**Comment by maxteufel** [comment]
:+1:
