### ISSUE TITLE
Improve camera

### ISSUE THREAD

**Issue by MaximeCheramy** [SuperTux/flexlay#73]
Currently the camera seems to be centered on Tux which is very annoying (too much movements). The following articles may help: 
- http://gamasutra.com/blogs/ItayKeren/20150511/243083/Scroll_Back_The_Theory_and_Practice_of_Cameras_in_SideScrollers.php
- http://supertux.lethargik.org/wiki/Cameras_in_Super_Mario

**Comment by Karkus476** [comment]
I'm not sure whether this is a bug in Flexlay. We only have a few types of cameras in SuperTux, and they are handled by the game itself, not the editor.

**Comment by MaximeCheramy** [comment]
Arg sorry, I've posted in the wrong project.
